'use client'

import { useState, useEffect } from 'react'
import { Search, Loader2, AlertCircle, ExternalLink, Sparkles, BookOpen, History, X, Download } from 'lucide-react'
import { getDemoQueryResponse } from '@/constants/demoData'
import { API_BASE_URL } from '@/lib/api'
import { QueryResultSkeleton } from '@/components/Skeleton'

interface Citation {
  document_id: string
  document_title: string
  citation: string | null
  chunk_text: string
  relevance_score: number
}

interface QueryResponse {
  query: string
  answer: string
  confidence_score: number
  citations: Citation[]
  chain_of_thought: string | null
  ambiguity_flags: string[]
  processing_time_ms: number
}

interface RecentQuery {
  query: string
  timestamp: number
}

interface QueryInterfaceProps {
  initialQuery?: string
  autoSubmit?: boolean
}

const RECENT_QUERIES_KEY = 'lex_recent_queries'
const MAX_RECENT_QUERIES = 10

export function QueryInterface({ initialQuery = '', autoSubmit = false }: QueryInterfaceProps) {
  const [query, setQuery] = useState(initialQuery)
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState<QueryResponse | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [hasAutoSubmitted, setHasAutoSubmitted] = useState(false)
  const [recentQueries, setRecentQueries] = useState<RecentQuery[]>([])
  const [showRecent, setShowRecent] = useState(false)

  // Load recent queries from localStorage
  useEffect(() => {
    const stored = localStorage.getItem(RECENT_QUERIES_KEY)
    if (stored) {
      try {
        setRecentQueries(JSON.parse(stored))
      } catch {
        // Ignore parse errors
      }
    }
  }, [])

  // Save query to recent history
  const saveToHistory = (queryText: string) => {
    const newQuery: RecentQuery = { query: queryText, timestamp: Date.now() }
    const updated = [newQuery, ...recentQueries.filter(q => q.query !== queryText)].slice(0, MAX_RECENT_QUERIES)
    setRecentQueries(updated)
    localStorage.setItem(RECENT_QUERIES_KEY, JSON.stringify(updated))
  }

  const clearHistory = () => {
    setRecentQueries([])
    localStorage.removeItem(RECENT_QUERIES_KEY)
  }

  // Auto-submit when initialQuery is provided
  useEffect(() => {
    if (autoSubmit && initialQuery && !hasAutoSubmitted) {
      setHasAutoSubmitted(true)
      submitQuery(initialQuery)
    }
  }, [autoSubmit, initialQuery, hasAutoSubmitted])

  const submitQuery = async (queryText: string) => {
    if (!queryText.trim()) return

    setLoading(true)
    setError(null)

    try {
      const res = await fetch(`${API_BASE_URL}/api/query/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: queryText,
          top_k: 5,
          include_graph_context: true,
          explain: true,
        }),
      })

      if (!res.ok) throw new Error('Query failed')

      const data = await res.json()
      setResponse(data)
      saveToHistory(queryText)
    } catch (err) {
      // For demo, show mock response instead of error
      setError(null)
      setResponse(getDemoQueryResponse(queryText))
      saveToHistory(queryText)
    } finally {
      setLoading(false)
    }
  }

  // Export response as text
  const exportResponse = () => {
    if (!response) return
    const content = `Query: ${response.query}

Answer:
${response.answer}

Confidence: ${Math.round(response.confidence_score * 100)}%

Sources:
${response.citations.map(c => `- ${c.document_title}${c.citation ? ` (${c.citation})` : ''}`).join('\n')}

Generated by Lex - Legal Cartography Platform
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `lex-query-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    submitQuery(query)
  }

  const getConfidenceConfig = (score: number) => {
    if (score >= 0.8) return { color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/20', label: 'High' }
    if (score >= 0.6) return { color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/20', label: 'Medium' }
    return { color: 'text-red-400', bg: 'bg-red-500/10 border-red-500/20', label: 'Low' }
  }

  return (
    <div className="space-y-6">
      {/* Search Form */}
      <form onSubmit={handleSubmit}>
        <div className="relative">
          <div className="flex gap-3">
            <div className="flex-1 relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-vulcan-500" />
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask a legal question... e.g., 'What are the FOIA disclosure requirements?'"
                className="w-full pl-12 pr-12 py-3.5 bg-vulcan-900 border border-vulcan-600 rounded-xl text-white placeholder-vulcan-500 focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-all"
              />
              {recentQueries.length > 0 && (
                <button
                  type="button"
                  onClick={() => setShowRecent(!showRecent)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 p-1 text-vulcan-500 hover:text-white transition-colors"
                  title="Recent queries"
                >
                  <History className="w-4 h-4" />
                </button>
              )}
            </div>
            <button
              type="submit"
              disabled={loading || !query.trim()}
              className="px-6 py-3.5 bg-accent hover:bg-accent-hover text-white rounded-xl font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 transition-all shadow-glow hover:shadow-glow-lg"
            >
              {loading ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Sparkles className="w-5 h-5" />
              )}
              Query
            </button>
          </div>

          {/* Recent Queries Dropdown */}
          {showRecent && recentQueries.length > 0 && (
            <div className="absolute top-full left-0 right-0 mt-2 bg-vulcan-800 border border-vulcan-700 rounded-xl shadow-xl z-10 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2 border-b border-vulcan-700">
                <span className="text-xs font-medium text-vulcan-400">Recent Queries</span>
                <button
                  type="button"
                  onClick={clearHistory}
                  className="text-xs text-vulcan-500 hover:text-red-400 transition-colors"
                >
                  Clear all
                </button>
              </div>
              <div className="max-h-60 overflow-y-auto">
                {recentQueries.map((rq, i) => (
                  <button
                    key={i}
                    type="button"
                    onClick={() => {
                      setQuery(rq.query)
                      setShowRecent(false)
                    }}
                    className="w-full text-left px-4 py-2.5 hover:bg-vulcan-700/50 transition-colors flex items-center justify-between group"
                  >
                    <span className="text-sm text-vulcan-200 truncate">{rq.query}</span>
                    <span className="text-xs text-vulcan-500">
                      {new Date(rq.timestamp).toLocaleDateString()}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      </form>

      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
          <p className="text-red-300 text-sm">{error}</p>
        </div>
      )}

      {/* Loading State */}
      {loading && <QueryResultSkeleton />}

      {/* Response Display */}
      {response && !loading && (
        <div className="space-y-6">
          {/* Answer Card */}
          <div className="bg-vulcan-800/50 rounded-xl border border-vulcan-700/50 overflow-hidden">
            <div className="px-5 py-4 border-b border-vulcan-700/50 flex items-center justify-between">
              <h3 className="font-semibold text-white flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-accent" />
                AI Response
              </h3>
              <div className="flex items-center gap-3">
                <button
                  onClick={exportResponse}
                  className="p-1.5 text-vulcan-400 hover:text-white hover:bg-vulcan-700 rounded-lg transition-colors"
                  title="Export response"
                >
                  <Download className="w-4 h-4" />
                </button>
                <span
                  className={`px-2.5 py-1 rounded-full text-xs font-medium border ${getConfidenceConfig(response.confidence_score).bg} ${getConfidenceConfig(response.confidence_score).color}`}
                >
                  {Math.round(response.confidence_score * 100)}% Confidence
                </span>
                <span className="text-xs text-vulcan-500">
                  {response.processing_time_ms.toFixed(0)}ms
                </span>
              </div>
            </div>
            <div className="p-5">
              <p className="text-vulcan-200 whitespace-pre-wrap leading-relaxed">{response.answer}</p>

              {/* Ambiguity Flags */}
              {response.ambiguity_flags.length > 0 && (
                <div className="mt-4 p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg">
                  <p className="text-xs font-medium text-amber-400 mb-1">Review Recommended</p>
                  <ul className="text-xs text-amber-300/80">
                    {response.ambiguity_flags.map((flag, i) => (
                      <li key={i}>{flag}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>

          {/* Citations */}
          <div>
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-vulcan-400" />
              Sources & Citations ({response.citations.length})
            </h3>
            <div className="space-y-2">
              {response.citations.map((citation, i) => (
                <div
                  key={i}
                  className="bg-vulcan-800/50 border border-vulcan-700/50 rounded-xl p-4 hover:border-accent/30 transition-all group"
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h4 className="font-medium text-white text-sm">{citation.document_title}</h4>
                      {citation.citation && (
                        <p className="text-xs font-mono text-accent mt-0.5">{citation.citation}</p>
                      )}
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      <span className={`text-xs font-medium px-2 py-0.5 rounded-full border ${getConfidenceConfig(citation.relevance_score).bg} ${getConfidenceConfig(citation.relevance_score).color}`}>
                        {Math.round(citation.relevance_score * 100)}%
                      </span>
                      <ExternalLink className="w-3.5 h-3.5 text-vulcan-500 group-hover:text-accent transition-colors" />
                    </div>
                  </div>
                  <p className="mt-2 text-xs text-vulcan-400 line-clamp-2">{citation.chunk_text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Chain of Thought */}
          {response.chain_of_thought && (
            <details className="bg-vulcan-800/50 border border-vulcan-700/50 rounded-xl overflow-hidden">
              <summary className="px-5 py-3 cursor-pointer text-sm font-medium text-vulcan-300 hover:bg-vulcan-700/30 transition-colors">
                View reasoning chain
              </summary>
              <div className="px-5 pb-4 pt-2 border-t border-vulcan-700/50">
                <pre className="text-xs text-vulcan-400 whitespace-pre-wrap font-mono bg-vulcan-900/50 p-3 rounded-lg">
                  {response.chain_of_thought}
                </pre>
              </div>
            </details>
          )}
        </div>
      )}

      {/* Empty State */}
      {!response && !loading && (
        <div className="text-center py-16">
          <div className="w-16 h-16 bg-vulcan-800 border border-vulcan-700 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Search className="w-8 h-8 text-vulcan-500" />
          </div>
          <h3 className="text-lg font-semibold text-white mb-2">Query the Legal Corpus</h3>
          <p className="text-vulcan-400 max-w-md mx-auto text-sm">
            Ask questions about regulations, statutes, or compliance requirements.
            Get answers with citations and confidence scores.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-2">
            {[
              'What are FOIA requirements?',
              'FERPA student privacy rules',
              'ADA compliance standards',
            ].map((suggestion) => (
              <button
                key={suggestion}
                onClick={() => setQuery(suggestion)}
                className="px-4 py-2 text-sm bg-vulcan-800 border border-vulcan-700 hover:border-accent/50 hover:bg-vulcan-700 rounded-lg text-vulcan-300 transition-all"
              >
                {suggestion}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
