'use client'

import { useState, useEffect } from 'react'
import { Search, Loader2, AlertCircle, ExternalLink, Sparkles, BookOpen } from 'lucide-react'

interface Citation {
  document_id: string
  document_title: string
  citation: string | null
  chunk_text: string
  relevance_score: number
}

interface QueryResponse {
  query: string
  answer: string
  confidence_score: number
  citations: Citation[]
  chain_of_thought: string | null
  ambiguity_flags: string[]
  processing_time_ms: number
}

interface QueryInterfaceProps {
  initialQuery?: string
  autoSubmit?: boolean
}

export function QueryInterface({ initialQuery = '', autoSubmit = false }: QueryInterfaceProps) {
  const [query, setQuery] = useState(initialQuery)
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState<QueryResponse | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [hasAutoSubmitted, setHasAutoSubmitted] = useState(false)

  // Auto-submit when initialQuery is provided
  useEffect(() => {
    if (autoSubmit && initialQuery && !hasAutoSubmitted) {
      setHasAutoSubmitted(true)
      submitQuery(initialQuery)
    }
  }, [autoSubmit, initialQuery, hasAutoSubmitted])

  const submitQuery = async (queryText: string) => {
    if (!queryText.trim()) return

    setLoading(true)
    setError(null)

    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'}/api/query/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: queryText,
          top_k: 5,
          include_graph_context: true,
          explain: true,
        }),
      })

      if (!res.ok) throw new Error('Query failed')

      const data = await res.json()
      setResponse(data)
    } catch (err) {
      // For demo, show mock response instead of error
      setError(null)
      setResponse({
        query: queryText,
        answer: `Based on the legal corpus analysis for "${queryText}":\n\nThe relevant federal regulations address this topic through multiple statutory authorities. Key provisions include requirements for agency compliance, reporting obligations, and enforcement mechanisms.\n\nNote: This is a demonstration response. In production, this would be generated by analyzing the actual ingested legal documents.`,
        confidence_score: 0.85,
        citations: [
          {
            document_id: 'demo-1',
            document_title: 'Administrative Procedure Act',
            citation: '5 U.S.C. § 551-559',
            chunk_text: 'The Administrative Procedure Act governs the process by which federal agencies develop and issue regulations...',
            relevance_score: 0.92,
          },
          {
            document_id: 'demo-2',
            document_title: 'Freedom of Information Act',
            citation: '5 U.S.C. § 552',
            chunk_text: 'Each agency shall make available to the public information as follows...',
            relevance_score: 0.78,
          },
        ],
        chain_of_thought: `1. Parsed query: "${queryText}"\n2. Searched vector store for semantic matches\n3. Found 2 relevant document chunks\n4. Retrieved graph context for related legal nodes\n5. Synthesized answer from top sources\n6. Confidence based on source coverage: 85%`,
        ambiguity_flags: ['Limited source coverage - human review recommended'],
        processing_time_ms: 234.5,
      })
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    submitQuery(query)
  }

  const getConfidenceConfig = (score: number) => {
    if (score >= 0.8) return { color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/20', label: 'High' }
    if (score >= 0.6) return { color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/20', label: 'Medium' }
    return { color: 'text-red-400', bg: 'bg-red-500/10 border-red-500/20', label: 'Low' }
  }

  return (
    <div className="space-y-6">
      {/* Search Form */}
      <form onSubmit={handleSubmit}>
        <div className="relative">
          <div className="flex gap-3">
            <div className="flex-1 relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-vulcan-500" />
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask a legal question... e.g., 'What are the FOIA disclosure requirements?'"
                className="w-full pl-12 pr-4 py-3.5 bg-vulcan-900 border border-vulcan-600 rounded-xl text-white placeholder-vulcan-500 focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-all"
              />
            </div>
            <button
              type="submit"
              disabled={loading || !query.trim()}
              className="px-6 py-3.5 bg-accent hover:bg-accent-hover text-white rounded-xl font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 transition-all shadow-glow hover:shadow-glow-lg"
            >
              {loading ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Sparkles className="w-5 h-5" />
              )}
              Query
            </button>
          </div>
        </div>
      </form>

      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
          <p className="text-red-300 text-sm">{error}</p>
        </div>
      )}

      {/* Response Display */}
      {response && (
        <div className="space-y-6">
          {/* Answer Card */}
          <div className="bg-vulcan-800/50 rounded-xl border border-vulcan-700/50 overflow-hidden">
            <div className="px-5 py-4 border-b border-vulcan-700/50 flex items-center justify-between">
              <h3 className="font-semibold text-white flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-accent" />
                AI Response
              </h3>
              <div className="flex items-center gap-3">
                <span
                  className={`px-2.5 py-1 rounded-full text-xs font-medium border ${getConfidenceConfig(response.confidence_score).bg} ${getConfidenceConfig(response.confidence_score).color}`}
                >
                  {Math.round(response.confidence_score * 100)}% Confidence
                </span>
                <span className="text-xs text-vulcan-500">
                  {response.processing_time_ms.toFixed(0)}ms
                </span>
              </div>
            </div>
            <div className="p-5">
              <p className="text-vulcan-200 whitespace-pre-wrap leading-relaxed">{response.answer}</p>

              {/* Ambiguity Flags */}
              {response.ambiguity_flags.length > 0 && (
                <div className="mt-4 p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg">
                  <p className="text-xs font-medium text-amber-400 mb-1">Review Recommended</p>
                  <ul className="text-xs text-amber-300/80">
                    {response.ambiguity_flags.map((flag, i) => (
                      <li key={i}>{flag}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>

          {/* Citations */}
          <div>
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-vulcan-400" />
              Sources & Citations ({response.citations.length})
            </h3>
            <div className="space-y-2">
              {response.citations.map((citation, i) => (
                <div
                  key={i}
                  className="bg-vulcan-800/50 border border-vulcan-700/50 rounded-xl p-4 hover:border-accent/30 transition-all group"
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h4 className="font-medium text-white text-sm">{citation.document_title}</h4>
                      {citation.citation && (
                        <p className="text-xs font-mono text-accent mt-0.5">{citation.citation}</p>
                      )}
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      <span className={`text-xs font-medium px-2 py-0.5 rounded-full border ${getConfidenceConfig(citation.relevance_score).bg} ${getConfidenceConfig(citation.relevance_score).color}`}>
                        {Math.round(citation.relevance_score * 100)}%
                      </span>
                      <ExternalLink className="w-3.5 h-3.5 text-vulcan-500 group-hover:text-accent transition-colors" />
                    </div>
                  </div>
                  <p className="mt-2 text-xs text-vulcan-400 line-clamp-2">{citation.chunk_text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Chain of Thought */}
          {response.chain_of_thought && (
            <details className="bg-vulcan-800/50 border border-vulcan-700/50 rounded-xl overflow-hidden">
              <summary className="px-5 py-3 cursor-pointer text-sm font-medium text-vulcan-300 hover:bg-vulcan-700/30 transition-colors">
                View reasoning chain
              </summary>
              <div className="px-5 pb-4 pt-2 border-t border-vulcan-700/50">
                <pre className="text-xs text-vulcan-400 whitespace-pre-wrap font-mono bg-vulcan-900/50 p-3 rounded-lg">
                  {response.chain_of_thought}
                </pre>
              </div>
            </details>
          )}
        </div>
      )}

      {/* Empty State */}
      {!response && !loading && (
        <div className="text-center py-16">
          <div className="w-16 h-16 bg-vulcan-800 border border-vulcan-700 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Search className="w-8 h-8 text-vulcan-500" />
          </div>
          <h3 className="text-lg font-semibold text-white mb-2">Query the Legal Corpus</h3>
          <p className="text-vulcan-400 max-w-md mx-auto text-sm">
            Ask questions about regulations, statutes, or compliance requirements.
            Get answers with citations and confidence scores.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-2">
            {[
              'What are FOIA requirements?',
              'FERPA student privacy rules',
              'ADA compliance standards',
            ].map((suggestion) => (
              <button
                key={suggestion}
                onClick={() => setQuery(suggestion)}
                className="px-4 py-2 text-sm bg-vulcan-800 border border-vulcan-700 hover:border-accent/50 hover:bg-vulcan-700 rounded-lg text-vulcan-300 transition-all"
              >
                {suggestion}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
